apiVersion: v1
kind: Service
metadata:
  name: percona-primary
spec:
  selector:
    app: percona
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: percona-replica
spec:
  selector:
    app: percona
  ports:
    - protocol: TCP
      port: 3306
